env:
  FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ETERNAL_COURAGE_435409_U8 }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # หรือเวอร์ชันที่คุณต้องการ
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Firebase Deploy
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ETERNAL_COURAGE_435409_U8 }}
        run: firebase deploy --token "$FIREBASE_SERVICE_ACCOUNT"
